### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AngeloCore** [highlightjs/hljs_org#13]
**Hello there!**

The `highlightjs` website looks so old and the "documentation" is a bit old tho..
So I am here to ask, can I rewrite the `highlightjs` website, I will use 2022 style, create docs, better home page and more!
I see that the current site is using python, but for the new one i will use [`react`](https://reactjs.org/), [`redux`](https://redux.js.org/) and [`nextjs`](https://nextjs.org/) or the new [`remixjs`](https://remix.run/)

The website will be so fresh and fast!

**Note:** My github profile does not have so many repositories, because I don't upload my codes to github

**PS:** If you agree, I will start working then I will make a pull request, if you like it, you use it, if you don't, then ok!

**Comment by joshgoebel** [comment]
Thanks for the offer, but we have a new website in the works.   What about our documentation do you feel is so terrible?

**Comment by AngeloCore** [comment]
Hey, thanks for the quick reply!
I hope the new website will be fire! 🔥
<br>

> What about our documentation do you feel is so terrible?

The documentation is not terrible, but the style is a bit old and can be more understandable, like the beta reactjs docs [here](https://beta.reactjs.org/)

**Comment by joshgoebel** [comment]
>  but the style is a bit old and can be more understandable

PRs are welcome (to the textual content), but I'm not sure we're interested in switching to a different documentation engine.  The current system is very familiar and requires 0 time or maintenance effort from maintainers.  Also our documentation set is (absolutely speaking) quite tiny...it's not like there are 100 API functions or pages to search thru.

Perhaps if there was a different Read the Docs Sphinx theme we could simply switch to (with very little effort) I might be curious seeing what someone had in mind.  But I personally find our docs "just fine" from a visual perspective... If someone had a few hours to spare on docs I think they'd benefit more from textual improvements rather than engine improvements.

> can be more understandable

If you want to make some textual changes please start with a small PR (or provide a rough overall plan or something) so we can first make sure we're in agreement on what your idea of "more understandable" is...

**Comment by joshgoebel** [comment]
Closing this as asked and answered.
