### ISSUE TITLE
Downloading a custom package contains not-minified css-files without root-container-rule

### ISSUE THREAD

**Issue by 0xnoob** [highlightjs/hljs_org#8]
**Describe the issue/behavior that seems buggy**
Downloading a custom package contains the non-minified CSS-files and the The `base16` folder is empty.  
They are also missing this common rule:
```css
.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
}
```
[The docs says:](https://highlightjs.readthedocs.io/en/latest/style-guide.html#typography-and-layout-dos-and-don-ts)
>If your theme exists within the core project you do not need to add these rules by hand as they are added to all themes by default during the build process.

Maybe something went wrong in the build process?

**Sample Code or Instructions to Reproduce**
 1. goto https://highlightjs.org/download/
 2. click [download]
 3. check the zip file for the above mentioned issues.

**Expected behavior**
The CSS-files should be minified, should include the common rule and the `base16` folder shouldnt' be empty.

**Comment by joshgoebel** [comment]
I see a few issues:

https://github.com/highlightjs/hljs_org/blob/master/hljs_org/lib.py#L128

- The CSS should come from the cached_path (where the CSS has been built and properly minified), not the source path. All our CSS now requires building, so the raw files are no good to hand out.
- Perhaps we need `glob("**")` now? Not sure. We need to pick up and zip not just `styles/*` now but `styles/base16/*` as well.

Honestly instead of this "one file at a time" approach if it would be any easier I think what would be much better:

- Zip up the entire `cached_path/**`
- Replace `highlight.min.js` with the custom build
- OR simply add `custom.min.js` beside the regular build

CC @highlightjs/core @isagalaev

**Comment by isagalaev** [comment]
Should be fixed by 6e6c79e.

I went with your suggestion to include everything in the cache dir, replacing highlight.min.js with the custom-built one. One minor regression is missing CHANGES.md, which used to be included in the download, but is absent from the CDN build and hence the cache dir.

**Comment by joshgoebel** [comment]
@0xnoob Can you confirm all looks good now?

**Comment by 0xnoob** [comment]
looks good to me!

**Comment by joshgoebel** [comment]
@isagalaev Thanks so much.  @0xnoob Thanks for reporting!
